# Generated by Django 5.1.4 on 2026-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("press", "Press release"),
                            ("event", "Event"),
                        ],
                        default="news",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("excerpt", models.CharField(blank=True, max_length=400)),
                ("body", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, max_length=600)),
                ("image_url", models.URLField(blank=True, max_length=600)),
                ("date", models.DateField(blank=True, null=True)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
