# Generated by Django 5.1.4 on 2026-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("caption", models.CharField(blank=True, max_length=400)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("events", "Events"),
                            ("achievements", "Achievements"),
                            ("community", "Community"),
                            ("reunion", "Reunion"),
                            ("other", "Other"),
                        ],
                        default="events",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("image_url", models.URLField(max_length=600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
