# Generated by Django 5.1.4 on 2026-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=120)),
                ("university", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=False)),
                ("photo_url", models.URLField(blank=True, max_length=600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "name"],
            },
        ),
    ]
