# Generated by Django 5.1.4 on 2026-06-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecmember",
            name="is_convening",
            field=models.BooleanField(default=False),
        ),
    ]
