# Generated by Django 5.1.4 on 2026-06-28 06:59

from django.db import migrations, models


PRESIDENT_BODY = """Assalamu Alaikum and warm greetings to every member, well-wisher, and friend of PUSAB. It is a profound honour to serve as President of this remarkable association — a family built not on convenience, but on a shared love for Bishwambarpur and a collective belief in the transformative power of education.

When PUSAB was founded in 2014, it was born out of a simple but powerful idea: that students from public universities, medical colleges, and engineering institutions who hail from the same upazila can — and should — stand together, support one another, and give back to the community that shaped them. Over a decade later, that idea has grown into a movement of more than 300 dedicated young minds.

Our journey has never been about prestige or personal gain. It has always been about service — tutoring the next generation of students, organising programmes that celebrate academic achievement, building bridges between villages and universities, and ensuring that no talented student from Bishwambarpur feels alone on the long road ahead.

As we move forward, my commitment is to deepen our roots in the community, broaden our reach across institutions, and create more structured pathways for students who need guidance, mentorship, and a sense of belonging. Every initiative we undertake — from felicitation ceremonies to community outreach — is a step toward a more connected and empowered Bishwambarpur.

I invite every member to carry the spirit of PUSAB with them: in their classrooms, in their communities, and in their character. Together, we are stronger than the sum of our parts. Together, we are PUSAB."""

SECRETARY_BODY = """Assalamu Alaikum to all members, supporters, and friends of PUSAB. Serving as General Secretary of this association is both a privilege and a responsibility I carry with deep gratitude and commitment.

Since our founding in 2014, PUSAB has stood for unity, service, and the belief that students from Bishwambarpur can achieve far more together than apart. My role is to keep that engine running — coordinating our programmes, supporting our members, and making sure every initiative reflects the values we hold dear.

A strong organisation is one where leadership is not concentrated at the top but shared freely across all levels. I am committed to keeping PUSAB open, transparent, and responsive to the needs of every member, wherever they study and whatever they pursue.

Together, let us keep building an association that uplifts students, strengthens our community, and carries the name of Bishwambarpur forward with pride."""


def seed_messages(apps, schema_editor):
    LeaderMessage = apps.get_model("committee", "LeaderMessage")
    LeaderMessage.objects.get_or_create(
        role="president",
        defaults={
            "name": "",
            "designation": "President, PUSAB",
            "session": "Session 2026",
            "quote": "Together, we are stronger than the sum of our parts. Together, we are PUSAB.",
            "body": PRESIDENT_BODY,
        },
    )
    LeaderMessage.objects.get_or_create(
        role="secretary",
        defaults={
            "name": "",
            "designation": "General Secretary, PUSAB",
            "session": "Session 2026",
            "quote": "A strong organisation is one where leadership is not concentrated at the top but shared freely across all levels.",
            "body": SECRETARY_BODY,
        },
    )


def unseed_messages(apps, schema_editor):
    LeaderMessage = apps.get_model("committee", "LeaderMessage")
    LeaderMessage.objects.filter(role__in=["president", "secretary"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("committee", "0002_ecmember_is_convening"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("secretary", "General Secretary"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("session", models.CharField(blank=True, max_length=40)),
                ("photo_url", models.URLField(blank=True, max_length=600)),
                ("quote", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role"],
            },
        ),
        migrations.RunPython(seed_messages, unseed_messages),
    ]
