# Generated by Django 5.1.4 on 2026-06-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FelicitationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("achiever", "Achiever (felicitated)"),
                            ("fresher", "Fresher (welcomed)"),
                        ],
                        default="achiever",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("image_url", models.URLField(blank=True, max_length=600)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Felicitation entries",
                "ordering": ["-year", "category", "name"],
            },
        ),
    ]
