/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConveningCommitteeRouteImport } from './routes/convening-committee'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SecretaryMessageRouteImport } from './routes/secretary-message'
import { Route as SayorRouteImport } from './routes/sayor'
import { Route as PublicityRouteImport } from './routes/publicity'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PresidentMessageRouteImport } from './routes/president-message'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as HonorBoardRouteImport } from './routes/honor-board'
import { Route as FelicitationRouteImport } from './routes/felicitation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ConveningCommitteeRoute = ConveningCommitteeRouteImport.update({
  id: '/convening-committee',
  path: '/convening-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryMessageRoute = SecretaryMessageRouteImport.update({
  id: '/secretary-message',
  path: '/secretary-message',
  getParentRoute: () => rootRouteImport,
} as any)
const SayorRoute = SayorRouteImport.update({
  id: '/sayor',
  path: '/sayor',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicityRoute = PublicityRouteImport.update({
  id: '/publicity',
  path: '/publicity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidentMessageRoute = PresidentMessageRouteImport.update({
  id: '/president-message',
  path: '/president-message',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorBoardRoute = HonorBoardRouteImport.update({
  id: '/honor-board',
  path: '/honor-board',
  getParentRoute: () => rootRouteImport,
} as any)
const FelicitationRoute = FelicitationRouteImport.update({
  id: '/felicitation',
  path: '/felicitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/convening-committee': typeof ConveningCommitteeRoute
  '/dashboard': typeof DashboardRoute
  '/felicitation': typeof FelicitationRoute
  '/honor-board': typeof HonorBoardRoute
  '/leadership': typeof LeadershipRoute
  '/moments': typeof MomentsRoute
  '/president-message': typeof PresidentMessageRoute
  '/programs': typeof ProgramsRoute
  '/publicity': typeof PublicityRoute
  '/sayor': typeof SayorRoute
  '/secretary-message': typeof SecretaryMessageRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/convening-committee': typeof ConveningCommitteeRoute
  '/dashboard': typeof DashboardRoute
  '/felicitation': typeof FelicitationRoute
  '/honor-board': typeof HonorBoardRoute
  '/leadership': typeof LeadershipRoute
  '/moments': typeof MomentsRoute
  '/president-message': typeof PresidentMessageRoute
  '/programs': typeof ProgramsRoute
  '/publicity': typeof PublicityRoute
  '/sayor': typeof SayorRoute
  '/secretary-message': typeof SecretaryMessageRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/convening-committee': typeof ConveningCommitteeRoute
  '/dashboard': typeof DashboardRoute
  '/felicitation': typeof FelicitationRoute
  '/honor-board': typeof HonorBoardRoute
  '/leadership': typeof LeadershipRoute
  '/moments': typeof MomentsRoute
  '/president-message': typeof PresidentMessageRoute
  '/programs': typeof ProgramsRoute
  '/publicity': typeof PublicityRoute
  '/sayor': typeof SayorRoute
  '/secretary-message': typeof SecretaryMessageRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/convening-committee'
    | '/dashboard'
    | '/felicitation'
    | '/honor-board'
    | '/leadership'
    | '/moments'
    | '/president-message'
    | '/programs'
    | '/publicity'
    | '/sayor'
    | '/secretary-message'
    | '/support'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/convening-committee'
    | '/dashboard'
    | '/felicitation'
    | '/honor-board'
    | '/leadership'
    | '/moments'
    | '/president-message'
    | '/programs'
    | '/publicity'
    | '/sayor'
    | '/secretary-message'
    | '/support'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/convening-committee'
    | '/dashboard'
    | '/felicitation'
    | '/honor-board'
    | '/leadership'
    | '/moments'
    | '/president-message'
    | '/programs'
    | '/publicity'
    | '/sayor'
    | '/secretary-message'
    | '/support'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ConveningCommitteeRoute: typeof ConveningCommitteeRoute
  DashboardRoute: typeof DashboardRoute
  FelicitationRoute: typeof FelicitationRoute
  HonorBoardRoute: typeof HonorBoardRoute
  LeadershipRoute: typeof LeadershipRoute
  MomentsRoute: typeof MomentsRoute
  PresidentMessageRoute: typeof PresidentMessageRoute
  ProgramsRoute: typeof ProgramsRoute
  PublicityRoute: typeof PublicityRoute
  SayorRoute: typeof SayorRoute
  SecretaryMessageRoute: typeof SecretaryMessageRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary-message': {
      id: '/secretary-message'
      path: '/secretary-message'
      fullPath: '/secretary-message'
      preLoaderRoute: typeof SecretaryMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayor': {
      id: '/sayor'
      path: '/sayor'
      fullPath: '/sayor'
      preLoaderRoute: typeof SayorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicity': {
      id: '/publicity'
      path: '/publicity'
      fullPath: '/publicity'
      preLoaderRoute: typeof PublicityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/president-message': {
      id: '/president-message'
      path: '/president-message'
      fullPath: '/president-message'
      preLoaderRoute: typeof PresidentMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honor-board': {
      id: '/honor-board'
      path: '/honor-board'
      fullPath: '/honor-board'
      preLoaderRoute: typeof HonorBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/felicitation': {
      id: '/felicitation'
      path: '/felicitation'
      fullPath: '/felicitation'
      preLoaderRoute: typeof FelicitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convening-committee': {
      id: '/convening-committee'
      path: '/convening-committee'
      fullPath: '/convening-committee'
      preLoaderRoute: typeof ConveningCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ConveningCommitteeRoute: ConveningCommitteeRoute,
  DashboardRoute: DashboardRoute,
  FelicitationRoute: FelicitationRoute,
  HonorBoardRoute: HonorBoardRoute,
  LeadershipRoute: LeadershipRoute,
  MomentsRoute: MomentsRoute,
  PresidentMessageRoute: PresidentMessageRoute,
  ProgramsRoute: ProgramsRoute,
  PublicityRoute: PublicityRoute,
  SayorRoute: SayorRoute,
  SecretaryMessageRoute: SecretaryMessageRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
